# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx expo export -p web']

[start]
cmd = 'npx serve dist -s -p $PORT'
